spring.application.name=${SPRING_APPLICATION_NAME}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}


#untuk upload image
spring.servlet.multipart.enabled=${SPRING_SERVLET_MULTIPART_ENABLED}
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}

#spring.devtools.restart.enabled=true
#ring.devtools.restart.pollInterval=1000
#spring.security.user.password=Test12345_
#spring.main.allow-bean-definition-overriding=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

logging.level.root=${LOGGING_LEVEL_ROOT}
#logging.level.com.example=debug
#logging.file.name=logs/app.log  # Nama file log yang akan dihasilkan
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n  # Format log di console

paymentgateway.duitku.callbackurl=${PAYMENTGATEWAY_DUITKU_CALLBACKURL}
paymentgateway.duitku.returnurl=${PAYMENTGATEWAY_DUITKU_RETURNURL}
paymentgateway.duitku.merchantcode=${PAYMENTGATEWAY_DUITKU_MERCHANTCODE}
paymentgateway.duitku.apikey=${PAYMENTGATEWAY_DUITKU_APIKEY}

#private static final String MERCHANT_CODE = "DS21299";
#private static final String API_KEY = "36d359f7edace8b47b99c6b733eb0313";