services:
    postgresql:
        image: postgres:16
        container_name: ticketonline_postgres
        ports:
            - "54322:5432"
        restart: unless-stopped
        environment:
            POSTGRES_DB: db_spring_event_ticket
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: fahmi123
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d db_spring_event_ticket"]
            interval: 5s
            timeout: 5s
            retries: 10
    backend:
        build:
            context: ./springboot-be-ticketonline
            dockerfile: Docker/Dockerfile.nginx.staging
            network: host
        container_name: ticketonline_backend
        ports:
            - "2005:80"
        restart: unless-stopped
        env_file:
            - ./springboot-be-ticketonline/.env
        volumes:
            - backend_uploads:/app/uploaded-images
        depends_on:
            postgresql:
                condition: service_healthy

    frontend:
        build: 
            context: ./react-fe-ticketonline
            dockerfile: Docker/Dockerfile.nginx.staging
            network: host
            args:
                VITE_API_BE_URL: ""
        container_name: ticketonline_frontend
        ports:
            - "1005:80"
        restart: unless-stopped
        depends_on:
            - backend

volumes:
    postgres_data:
    backend_uploads:
