FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests -e

FROM eclipse-temurin:17-jre

WORKDIR /app

RUN apt-get update \
    && apt-get install -y nginx supervisor \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/target/*.jar /app/app.jar

COPY Docker/Config/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY Docker/Services/supervisord.nginx.conf /etc/supervisor/conf.d/supervisord.conf
COPY Docker/Services/start-container.sh /app/start-container.sh

RUN chmod +x /app/start-container.sh

EXPOSE 80

CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]